version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # check our pom.xml
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"

  # check our docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  # check our npm in project
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "monthly"

  # check our npm for dev
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  # Check our tf -aws
  - package-ecosystem: "terraform"
    directory: "/aws"
    schedule:
      interval: "monthly"

  # Check our tf -azure
  - package-ecosystem: "terraform"
    directory: "/azure"
    schedule:
      interval: "monthly"

    # Check our tf -gcp
  - package-ecosystem: "terraform"
    directory: "/gcp"
    schedule:
      interval: "monthly"
