apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-challenge-53
  namespace: default
spec:
  progressDeadlineSeconds: 20
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secret-challenge-53
  template:
    metadata:
      labels:
        app: secret-challenge-53
      name: secret-challenge-53
    spec:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      containers:
      - image: jeroenwillemsen/wrongsecrets-challenge53:1.11.2
        name: secret-challenge-53
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: '32Mi'
            cpu: '50m'
            ephemeral-storage: '100Mi'
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          privileged: false
          seccompProfile:
            type: RuntimeDefault
      volumes:
        - name: 'ephemeral'
          emptyDir: { }
