apiVersion: v1
kind: Service
metadata:
  name: wrongsecrets-ctf
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
    - name: mcp
      port: 8090
  selector:
    app: secret-challenge-ctf
