name: DAST with ZAP

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-dast:
    name: DAST test with ZAP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
      - name: Clean install
        run: ./mvnw clean install -DskipTests -Ddependency-check.skip -Dcyclonedx.skip=true
      - name: Start wrongsecrets
        run: nohup ./mvnw spring-boot:run -Dspring-boot.run.profiles=without-vault &
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          allow_issue_writing: false
          docker_name: "owasp/zap2docker-stable"
          target: "http://localhost:8080"
          rules_file_name: config/zap/rule-config.tsv
          fail_action: true
