name: Javadoc and Swaggerdoc generator

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: read
jobs:
  javaDocGenerator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
      - name: Clean install
        run: ./mvnw --no-transfer-progress clean install -DskipTests -Ddependency-check.skip -Dcyclonedx.skip=true -Dexec.skip
      - name: Show npm logs on failure
        if: failure()
        run: |
          ls -la /home/runner/.npm/_logs || true
          cat /home/runner/.npm/_logs/*-debug-0.log || true
      - name: Compile javadoc
        run: ./mvnw --no-transfer-progress compile javadoc:javadoc
      - name: Start wrongsecrets
        run: nohup ./mvnw --no-transfer-progress spring-boot:run -Dspring-boot.run.profiles=without-vault &
      - name: Compile javadocs
        run: ./mvnw --no-transfer-progress compile javadoc:javadoc
      - name: Generate swaggerdoc
        run: ./mvnw --no-transfer-progress springdoc-openapi:generate
      - name: Upload swagger api doc
        uses: actions/upload-artifact@v4
        with:
         name: apidocs
         path: target/openapi.json
      - name: Upload javadoc
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/site
