name: Pre-commit check

# Controls when the workflow will run
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  TF_DOCS_VERSION: v0.19.0
  TFLINT_VERSION: v0.53.0
  TRIVY_VERSION: 0.58.0
permissions:
  contents: read
jobs:
  pre-commit:
    name: Pre-commit check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Format python code with black
        uses: psf/black@stable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "23"
      - name: Install npm dependencies
        run: npm install
      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{env.TFLINT_VERSION}}
      - name: Setup Terraform docs
        run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/${{env.TF_DOCS_VERSION}}/terraform-docs-${{env.TF_DOCS_VERSION}}-linux-amd64.tar.gz -O terraform_docs.tar.gz
          tar -zxvf terraform_docs.tar.gz terraform-docs
          chmod +x terraform-docs
          mv terraform-docs /usr/local/bin/
      - name: Setup trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v${{env.TRIVY_VERSION}}/trivy_${{env.TRIVY_VERSION}}_Linux-64bit.deb
          sudo dpkg -i trivy_${{env.TRIVY_VERSION}}_Linux-64bit.deb
      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.1
      - name: pre-commit-ci-lite
        uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
